# Generated by Django 3.0.8 on 2020-11-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='nickname',
            field=models.CharField(default='nameD', max_length=50),
        ),
    ]
