# Generated by Django 3.0.8 on 2020-11-29 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0002_costumer_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumer',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='profil',
            field=models.ImageField(height_field='height_field', upload_to='media/image', width_field='width_field'),
        ),
    ]
