# Generated by Django 3.0.8 on 2020-12-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0004_auto_20201216_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='profil',
            field=models.ImageField(default='media/image/IMG_20191007_233026_695.jpg', height_field='height_field', upload_to='media/image', width_field='width_field'),
        ),
    ]
