# Generated by Django 3.0.8 on 2020-12-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0006_costumer_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='background',
            field=models.ImageField(default='media/image/IMG_20191007_233026_695.jpg', height_field=600, upload_to='media/bgimg'),
        ),
    ]
