# Generated by Django 3.0.8 on 2020-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0007_auto_20201217_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='width_field2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='background',
            field=models.ImageField(default='media/image/IMG_20191007_233026_695.jpg', height_field=600, upload_to='media/bgimg', width_field='width_field2'),
        ),
    ]
