# Generated by Django 3.0.8 on 2020-12-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0010_auto_20201218_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(default='gmail.gmail.com', max_length=254),
        ),
    ]
