# Generated by Django 3.0.8 on 2020-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appb', '0011_auto_20201218_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(default='gmail@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='nameB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='nameD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
